"""
Application-wide constants.
Centralizing constants avoids magic strings scattered across the codebase.
"""

# Intent labels
INTENT_PAYMENT_ISSUE = "payment_issue"
INTENT_REFUND_REQUEST = "refund_request"
INTENT_ACCOUNT_LOCKED = "account_locked"
INTENT_TECHNICAL_BUG = "technical_bug"
INTENT_FEATURE_REQUEST = "feature_request"
INTENT_SUBSCRIPTION_CANCEL = "subscription_cancel"
INTENT_INVOICE_PROBLEM = "invoice_problem"
INTENT_SHIPPING_DELAY = "shipping_delay"
INTENT_GENERAL_INQUIRY = "general_inquiry"

ALL_INTENTS = [
    INTENT_PAYMENT_ISSUE, INTENT_REFUND_REQUEST, INTENT_ACCOUNT_LOCKED,
    INTENT_TECHNICAL_BUG, INTENT_FEATURE_REQUEST, INTENT_SUBSCRIPTION_CANCEL,
    INTENT_INVOICE_PROBLEM, INTENT_SHIPPING_DELAY, INTENT_GENERAL_INQUIRY,
]

# Priority levels
PRIORITY_CRITICAL = "critical"
PRIORITY_HIGH = "high"
PRIORITY_MEDIUM = "medium"
PRIORITY_LOW = "low"

ALL_PRIORITIES = [PRIORITY_CRITICAL, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW]

# Model types
MODEL_BASELINE = "baseline"
MODEL_TRANSFORMER = "transformer"

# API
DEFAULT_MODEL_TYPE = MODEL_BASELINE
MIN_TEXT_LENGTH = 3
MAX_TEXT_LENGTH = 512
TOP_N_INTENTS = 3
MAX_KEYWORDS = 5
